/*
 * AI provenance notice:
 * The initial implementation of this file was generated by OpenAI Codex from
 * requirements supplied by the repository owner. It was not manually authored
 * by the repository owner. Subsequent changes, if any, are recorded in version
 * control.
 */

#pragma once

import <atomic>;
import <cassert>;
import <compare>;
import <concepts>;
import <cstddef>;
import <iterator>;
import <memory>;
import <mutex>;
import <optional>;
import <span>;
import <type_traits>;
import <utility>;


// Any combination of std::shared_ptr and std::weak_ptr could be used here
template <typename T>
struct IsSharedOrWeakPtr : std::false_type {};

template <typename T>
struct IsSharedOrWeakPtr<std::shared_ptr<T>> : std::true_type {};

template <typename T>
struct IsSharedOrWeakPtr<std::weak_ptr<T>> : std::true_type {};

template <typename T>
concept SharedOrWeakPtr = IsSharedOrWeakPtr<std::remove_cvref_t<T>>::value;

template <SharedOrWeakPtr TPtrA, SharedOrWeakPtr TPtrB>
bool PointersHaveSameControlBlock(const TPtrA& a, const TPtrB& b)
{
    return !a.owner_before(b) && !b.owner_before(a);
}


template<typename T>
concept RingQueueElement =
	std::is_object_v<T> &&
	!std::is_const_v<T> &&
	!std::is_volatile_v<T> &&
	std::destructible<T>;


// Fixed-capacity ring buffer whose backing storage is allocated at construction.
// Ring operations never allocate or resize that storage; T's operations may.
// The container is not internally synchronized. Callers must serialize shared
// access, allowing it to participate in a larger locking protocol.
template<RingQueueElement T>
class TRingQueue final
{
public:
	using value_type = T;
	using size_type = std::size_t;
	using reference = value_type&;
	using const_reference = const value_type&;

	explicit TRingQueue(const size_type Capacity)
		: Capacity(Capacity)
		, Storage(Capacity == 0 ? nullptr : AllocatorTraits::allocate(Allocator, Capacity))
	{
	}

	~TRingQueue()
	{
		Reset();
	}

	TRingQueue(const TRingQueue&) = delete;
	TRingQueue& operator=(const TRingQueue&) = delete;

	TRingQueue(TRingQueue&& Other) noexcept
		: Capacity(std::exchange(Other.Capacity, 0))
		, Size(std::exchange(Other.Size, 0))
		, Head(std::exchange(Other.Head, 0))
		, Tail(std::exchange(Other.Tail, 0))
		, Storage(std::exchange(Other.Storage, nullptr))
	{
	}

	TRingQueue& operator=(TRingQueue&& Other) noexcept
	{
		if (this != &Other)
		{
			Reset();

			Capacity = std::exchange(Other.Capacity, 0);
			Size = std::exchange(Other.Size, 0);
			Head = std::exchange(Other.Head, 0);
			Tail = std::exchange(Other.Tail, 0);
			Storage = std::exchange(Other.Storage, nullptr);
		}

		return *this;
	}

	[[nodiscard]] size_type capacity() const noexcept
	{
		return Capacity;
	}

	[[nodiscard]] size_type size() const noexcept
	{
		return Size;
	}

	[[nodiscard]] bool empty() const noexcept
	{
		return Size == 0;
	}

	[[nodiscard]] bool full() const noexcept
	{
		return Size == Capacity;
	}

	[[nodiscard]] reference front() noexcept
	{
		assert(!empty());
		return Storage[Head];
	}

	[[nodiscard]] const_reference front() const noexcept
	{
		assert(!empty());
		return Storage[Head];
	}

	[[nodiscard]] reference back() noexcept
	{
		assert(!empty());
		return Storage[Tail == 0 ? Capacity - 1 : Tail - 1];
	}

	[[nodiscard]] const_reference back() const noexcept
	{
		assert(!empty());
		return Storage[Tail == 0 ? Capacity - 1 : Tail - 1];
	}

	template<typename... TArguments>
		requires std::constructible_from<value_type, TArguments...>
	[[nodiscard]] bool try_emplace(TArguments&&... Arguments)
	{
		if (full())
		{
			return false;
		}

		AllocatorTraits::construct(
			Allocator,
			Storage + Tail,
			std::forward<TArguments>(Arguments)...);

		Tail = Advance(Tail);
		++Size;

		return true;
	}

	[[nodiscard]] bool try_push(const value_type& Value)
		requires std::constructible_from<value_type, const value_type&>
	{
		return try_emplace(Value);
	}

	[[nodiscard]] bool try_push(value_type&& Value)
		requires std::constructible_from<value_type, value_type&&>
	{
		return try_emplace(std::move(Value));
	}

	void pop() noexcept
	{
		assert(!empty());

		AllocatorTraits::destroy(Allocator, Storage + Head);
		Head = Advance(Head);
		--Size;
	}

	[[nodiscard]] std::optional<value_type> try_pop() noexcept
		requires std::is_nothrow_move_constructible_v<value_type>
	{
		if (empty())
		{
			return std::nullopt;
		}

		std::optional<value_type> Result{
			std::in_place,
			std::move(front())
		};

		pop();
		return Result;
	}

    // Moves into caller-owned objects and returns the populated portion of the
    // destination. The returned span never refers to this queue's storage.
    template <typename Predicate = std::nullptr_t>
    [[nodiscard]] std::span<value_type> pop_into(std::span<value_type> Destination, Predicate&& predicate = nullptr)
        requires
            std::is_nothrow_move_constructible_v<value_type> &&
            std::is_nothrow_move_assignable_v<value_type>
    {
        const size_type OriginalSize = Size;
        size_type NumberPopped = 0;

        for (size_type Index = 0; Index < OriginalSize; ++Index)
        {
            value_type Current = std::move(front());
            pop();

            bool predicatePassed = true;

            if constexpr (!std::is_same_v<std::remove_cvref_t<Predicate>, std::nullptr_t>)
            {
                predicatePassed = std::invoke(predicate, Current);
            }

            if (NumberPopped < Destination.size() && predicatePassed)
            {
                Destination[NumberPopped++] = std::move(Current);
            }
            else
            {
                [[maybe_unused]] const bool success = try_push(std::move(Current));
                assert(success && "Failed to push inside TRingQueue's pop_into.");
            }
        }

        return Destination.first(NumberPopped);
    }

	void clear() noexcept
	{
		while (!empty())
		{
			pop();
		}
	}

private:
	// Random-access iterator over the ring's logical order. LogicalIndex is a plain,
	// non-wrapping offset from Head; only dereferencing maps it onto physical storage
	// via modulo Capacity, so iterator arithmetic never needs to know about wraparound.
	// Invalidated the same way any other view of Storage/Head/Tail/Size would be: by a
	// subsequent push, pop, clear, move, or destruction of the queue.
	template<bool IsConst>
	class Iterator
	{
	public:
		using iterator_concept = std::random_access_iterator_tag;
		using iterator_category = std::random_access_iterator_tag;
		using value_type = T;
		using difference_type = std::ptrdiff_t;
		using pointer = std::conditional_t<IsConst, const value_type*, value_type*>;
		using reference = std::conditional_t<IsConst, const value_type&, value_type&>;

		Iterator() noexcept = default;

		// Allows iterator -> const_iterator conversion. Templated on OtherIsConst (rather
		// than just taking Iterator<false>) so this is never mistaken for IsConst's own
		// copy constructor: a constructor template is never treated as a copy/move
		// constructor, even when it could match that signature after instantiation.
		template<bool OtherIsConst>
			requires (IsConst && !OtherIsConst)
		Iterator(const Iterator<OtherIsConst>& Other) noexcept
			: Storage(Other.Storage)
			, Capacity(Other.Capacity)
			, Head(Other.Head)
			, LogicalIndex(Other.LogicalIndex)
		{
		}

		[[nodiscard]] reference operator*() const noexcept { return Storage[PhysicalIndex(0)]; }
		[[nodiscard]] pointer operator->() const noexcept { return Storage + PhysicalIndex(0); }
		[[nodiscard]] reference operator[](const difference_type Offset) const noexcept { return Storage[PhysicalIndex(Offset)]; }

		Iterator& operator++() noexcept { ++LogicalIndex; return *this; }
		Iterator operator++(int) noexcept { Iterator Result = *this; ++*this; return Result; }
		Iterator& operator--() noexcept { --LogicalIndex; return *this; }
		Iterator operator--(int) noexcept { Iterator Result = *this; --*this; return Result; }

		Iterator& operator+=(const difference_type Offset) noexcept { LogicalIndex += Offset; return *this; }
		Iterator& operator-=(const difference_type Offset) noexcept { LogicalIndex -= Offset; return *this; }

		[[nodiscard]] friend Iterator operator+(Iterator It, const difference_type Offset) noexcept { It += Offset; return It; }
		[[nodiscard]] friend Iterator operator+(const difference_type Offset, Iterator It) noexcept { It += Offset; return It; }
		[[nodiscard]] friend Iterator operator-(Iterator It, const difference_type Offset) noexcept { It -= Offset; return It; }
		[[nodiscard]] friend difference_type operator-(const Iterator& Left, const Iterator& Right) noexcept { return Left.LogicalIndex - Right.LogicalIndex; }

		[[nodiscard]] friend bool operator==(const Iterator&, const Iterator&) noexcept = default;
		[[nodiscard]] friend auto operator<=>(const Iterator& Left, const Iterator& Right) noexcept { return Left.LogicalIndex <=> Right.LogicalIndex; }

	private:
		friend class TRingQueue;
		friend class Iterator<!IsConst>;

		using StoragePointer = std::conditional_t<IsConst, const value_type*, value_type*>;

		Iterator(StoragePointer Storage, const size_type Capacity, const size_type Head, const difference_type LogicalIndex) noexcept
			: Storage(Storage)
			, Capacity(Capacity)
			, Head(Head)
			, LogicalIndex(LogicalIndex)
		{
		}

		[[nodiscard]] size_type PhysicalIndex(const difference_type Offset) const noexcept
		{
			return (Head + static_cast<size_type>(LogicalIndex + Offset)) % Capacity;
		}

		StoragePointer Storage = nullptr;
		size_type Capacity = 0;
		size_type Head = 0;
		difference_type LogicalIndex = 0;
	};

public:
	using iterator = Iterator<false>;
	using const_iterator = Iterator<true>;

	[[nodiscard]] iterator begin() noexcept { return iterator(Storage, Capacity, Head, 0); }
	[[nodiscard]] iterator end() noexcept { return iterator(Storage, Capacity, Head, static_cast<std::ptrdiff_t>(Size)); }
	[[nodiscard]] const_iterator begin() const noexcept { return const_iterator(Storage, Capacity, Head, 0); }
	[[nodiscard]] const_iterator end() const noexcept { return const_iterator(Storage, Capacity, Head, static_cast<std::ptrdiff_t>(Size)); }
	[[nodiscard]] const_iterator cbegin() const noexcept { return begin(); }
	[[nodiscard]] const_iterator cend() const noexcept { return end(); }

private:
	using AllocatorType = std::allocator<value_type>;
	using AllocatorTraits = std::allocator_traits<AllocatorType>;

	[[nodiscard]] size_type Advance(const size_type Index) const noexcept
	{
		return Index + 1 == Capacity ? 0 : Index + 1;
	}

	void Reset() noexcept
	{
		clear();

		if (Storage != nullptr)
		{
			AllocatorTraits::deallocate(Allocator, Storage, Capacity);
		}

		Capacity = 0;
		Head = 0;
		Tail = 0;
		Storage = nullptr;
	}

	[[no_unique_address]] AllocatorType Allocator;
	size_type Capacity { 0 };
	size_type Size { 0 };
	size_type Head { 0 };
	size_type Tail { 0 };
	value_type* Storage { nullptr };
};

enum class TStateMachineState
{
    NotStarted = 0,
    InProgress,
    Stopping_Gracefully,
    Stopped,
};

template <typename T>
concept BasicLockable =
    requires(T mutex)
{
    mutex.lock();
    mutex.unlock();
};

template<typename T = TStateMachineState, typename TMutex = std::mutex>
    requires
        std::is_trivially_copyable_v<T> &&
        std::semiregular<T> &&
        std::totally_ordered<T> &&
        BasicLockable<TMutex>
class TStateMachine
{
public:

    [[nodiscard]] T GetState() const noexcept { return _state.load(std::memory_order_relaxed); }

    // Returns the new state if transition was successful
    virtual std::optional<T> SwitchToState(const T newState)
    {
        std::unique_lock<TMutex> lock(_state_mutex);

        const std::optional<T> result = SwitchToStateLocked(lock, newState);

        if (result)
        {
            lock.unlock();
            OnStateTransitionUnlocked(newState);
        }

        return result;
    }

protected:

    virtual ~TStateMachine() = default;

    // Same as SwitchToState, but the caller must already hold _state_mutex.
    // On success, the caller is responsible for calling
    // PostStateTransitionMutexUnLocked(newState) itself, after unlocking.
    std::optional<T> SwitchToStateLocked(const std::unique_lock<TMutex>& stateLock, const T newState)
    {
        if (!stateLock.owns_lock() || stateLock.mutex() != &_state_mutex)
        {
            assert(false && "SwitchToStateLocked requires this state machine's mutex.");
            return std::nullopt;
        }

        const auto oldState = GetState();

        if ((oldState == newState) || !IsStateTransitionAllowedLocked(oldState, newState))
        {
            return std::nullopt;
        }

        _state.store(newState, std::memory_order_relaxed);

        if (!OnStateTransitionLocked(newState))
        {
            _state.store(oldState, std::memory_order_relaxed);
            return std::nullopt;
        }

        return newState;
    }

    virtual bool IsStateTransitionAllowedLocked(const T fromState, const T toState) const { return toState > fromState; };

    // Return false if transition should be reverted. Last chance for the implementation to roll back changes if something critically goes wrong in this callback.
    virtual bool OnStateTransitionLocked([[maybe_unused]] const T newState) noexcept { return true; };
    virtual void OnStateTransitionUnlocked([[maybe_unused]] const T newState) noexcept {};

    mutable TMutex _state_mutex;

private:
    std::atomic<T> _state{ T{} };
};
