/*
 * AI provenance notice:
 * The initial implementation of this file was generated by OpenAI Codex from
 * requirements supplied by the repository owner. It was not manually authored
 * by the repository owner. Subsequent changes, if any, are recorded in version
 * control.
 */

#pragma once

import <atomic>;
import <cassert>;
import <concepts>;
import <cstddef>;
import <memory>;
import <mutex>;
import <optional>;
import <span>;
import <type_traits>;
import <utility>;


// Any combination of std::shared_ptr and std::weak_ptr could be used here
template <typename T>
struct IsSharedOrWeakPtr : std::false_type {};

template <typename T>
struct IsSharedOrWeakPtr<std::shared_ptr<T>> : std::true_type {};

template <typename T>
struct IsSharedOrWeakPtr<std::weak_ptr<T>> : std::true_type {};

template <typename T>
concept SharedOrWeakPtr = IsSharedOrWeakPtr<std::remove_cvref_t<T>>::value;

template <SharedOrWeakPtr TPtrA, SharedOrWeakPtr TPtrB>
bool PointersHaveSameControlBlock(const TPtrA& a, const TPtrB& b)
{
    return !a.owner_before(b) && !b.owner_before(a);
}


template<typename T>
concept RingQueueElement =
	std::is_object_v<T> &&
	!std::is_const_v<T> &&
	!std::is_volatile_v<T> &&
	std::destructible<T>;


// Fixed-capacity ring buffer whose backing storage is allocated at construction.
// Ring operations never allocate or resize that storage; T's operations may.
// The container is not internally synchronized. Callers must serialize shared
// access, allowing it to participate in a larger locking protocol.
template<RingQueueElement T>
class TRingQueue final
{
public:
	using value_type = T;
	using size_type = std::size_t;
	using reference = value_type&;
	using const_reference = const value_type&;

	explicit TRingQueue(const size_type Capacity)
		: Capacity(Capacity)
		, Storage(Capacity == 0 ? nullptr : AllocatorTraits::allocate(Allocator, Capacity))
	{
	}

	~TRingQueue()
	{
		Reset();
	}

	TRingQueue(const TRingQueue&) = delete;
	TRingQueue& operator=(const TRingQueue&) = delete;

	TRingQueue(TRingQueue&& Other) noexcept
		: Capacity(std::exchange(Other.Capacity, 0))
		, Size(std::exchange(Other.Size, 0))
		, Head(std::exchange(Other.Head, 0))
		, Tail(std::exchange(Other.Tail, 0))
		, Storage(std::exchange(Other.Storage, nullptr))
	{
	}

	TRingQueue& operator=(TRingQueue&& Other) noexcept
	{
		if (this != &Other)
		{
			Reset();

			Capacity = std::exchange(Other.Capacity, 0);
			Size = std::exchange(Other.Size, 0);
			Head = std::exchange(Other.Head, 0);
			Tail = std::exchange(Other.Tail, 0);
			Storage = std::exchange(Other.Storage, nullptr);
		}

		return *this;
	}

	[[nodiscard]] size_type capacity() const noexcept
	{
		return Capacity;
	}

	[[nodiscard]] size_type size() const noexcept
	{
		return Size;
	}

	[[nodiscard]] bool empty() const noexcept
	{
		return Size == 0;
	}

	[[nodiscard]] bool full() const noexcept
	{
		return Size == Capacity;
	}

	[[nodiscard]] reference front() noexcept
	{
		assert(!empty());
		return Storage[Head];
	}

	[[nodiscard]] const_reference front() const noexcept
	{
		assert(!empty());
		return Storage[Head];
	}

	[[nodiscard]] reference back() noexcept
	{
		assert(!empty());
		return Storage[Tail == 0 ? Capacity - 1 : Tail - 1];
	}

	[[nodiscard]] const_reference back() const noexcept
	{
		assert(!empty());
		return Storage[Tail == 0 ? Capacity - 1 : Tail - 1];
	}

	template<typename... TArguments>
		requires std::constructible_from<value_type, TArguments...>
	[[nodiscard]] bool try_emplace(TArguments&&... Arguments)
	{
		if (full())
		{
			return false;
		}

		AllocatorTraits::construct(
			Allocator,
			Storage + Tail,
			std::forward<TArguments>(Arguments)...);

		Tail = Advance(Tail);
		++Size;

		return true;
	}

	[[nodiscard]] bool try_push(const value_type& Value)
		requires std::constructible_from<value_type, const value_type&>
	{
		return try_emplace(Value);
	}

	[[nodiscard]] bool try_push(value_type&& Value)
		requires std::constructible_from<value_type, value_type&&>
	{
		return try_emplace(std::move(Value));
	}

	void pop() noexcept
	{
		assert(!empty());

		AllocatorTraits::destroy(Allocator, Storage + Head);
		Head = Advance(Head);
		--Size;
	}

	[[nodiscard]] std::optional<value_type> try_pop() noexcept
		requires std::is_nothrow_move_constructible_v<value_type>
	{
		if (empty())
		{
			return std::nullopt;
		}

		std::optional<value_type> Result{
			std::in_place,
			std::move(front())
		};

		pop();
		return Result;
	}

	// Moves into caller-owned objects and returns the populated portion of the
	// destination. The returned span never refers to this queue's storage.
	[[nodiscard]] std::span<value_type> pop_into(std::span<value_type> Destination) noexcept
		requires std::is_nothrow_move_assignable_v<value_type>
	{
		const size_type NumberToPop = (Size < Destination.size() ? Size : Destination.size());

		for (size_type Index = 0; Index < NumberToPop; ++Index)
		{
			Destination[Index] = std::move(front());
			pop();
		}

		return Destination.first(NumberToPop);
    }

    template <typename Predicate>
        requires std::predicate<Predicate&, const value_type&>
    [[nodiscard]] std::span<value_type> pop_into(std::span<value_type> Destination, Predicate&& predicate)
        requires
            std::is_nothrow_move_constructible_v<value_type>&&
            std::is_nothrow_move_assignable_v<value_type>
    {
        const size_type OriginalSize = Size;
        size_type NumberPopped = 0;

        for (size_type Index = 0; Index < OriginalSize; ++Index)
        {
            value_type Current = std::move(front());
            pop();

            if (NumberPopped < Destination.size() && std::invoke(predicate, Current))
            {
                Destination[NumberPopped++] = std::move(Current);
            }
            else
            {
                [[maybe_unused]] const bool success = try_push(std::move(Current));
                assert(success && "Failed to push inside TRingQueue's pop_into.");
            }
        }

        return Destination.first(NumberPopped);
    }

	void clear() noexcept
	{
		while (!empty())
		{
			pop();
		}
	}

private:
	using AllocatorType = std::allocator<value_type>;
	using AllocatorTraits = std::allocator_traits<AllocatorType>;

	[[nodiscard]] size_type Advance(const size_type Index) const noexcept
	{
		return Index + 1 == Capacity ? 0 : Index + 1;
	}

	void Reset() noexcept
	{
		clear();

		if (Storage != nullptr)
		{
			AllocatorTraits::deallocate(Allocator, Storage, Capacity);
		}

		Capacity = 0;
		Head = 0;
		Tail = 0;
		Storage = nullptr;
	}

	[[no_unique_address]] AllocatorType Allocator;
	size_type Capacity { 0 };
	size_type Size { 0 };
	size_type Head { 0 };
	size_type Tail { 0 };
	value_type* Storage { nullptr };
};

enum class TStateMachineState
{
    NotStarted = 0,
    InProgress,
    Stopping_Gracefully,
    Stopped,
};

template <typename T>
concept BasicLockable =
    requires(T mutex)
{
    mutex.lock();
    mutex.unlock();
};

template<typename T = TStateMachineState, typename TMutex = std::mutex>
    requires
        std::is_trivially_copyable_v<T> &&
        std::semiregular<T> &&
        std::totally_ordered<T> &&
        BasicLockable<TMutex>
class TStateMachine
{
public:

    [[nodiscard]] T GetState() const noexcept { return _state.load(std::memory_order_relaxed); }

    // Returns the new state if transition was successful
    virtual std::optional<T> SwitchToState(const T newState)
    {
        std::unique_lock<TMutex> lock(_state_mutex);

        const std::optional<T> result = SwitchToStateLocked(lock, newState);

        if (result)
        {
            lock.unlock();
            OnStateTransitionUnlocked(newState);
        }

        return result;
    }

protected:

    virtual ~TStateMachine() = default;

    // Same as SwitchToState, but the caller must already hold _state_mutex.
    // On success, the caller is responsible for calling
    // PostStateTransitionMutexUnLocked(newState) itself, after unlocking.
    std::optional<T> SwitchToStateLocked(const std::unique_lock<TMutex>& stateLock, const T newState)
    {
        if (!stateLock.owns_lock() || stateLock.mutex() != &_state_mutex)
        {
            assert(false && "SwitchToStateLocked requires this state machine's mutex.");
            return std::nullopt;
        }

        const auto oldState = GetState();

        if (!IsStateTransitionAllowedLocked(oldState, newState))
        {
            return std::nullopt;
        }

        _state.store(newState, std::memory_order_relaxed);

        if (!OnStateTransitionLocked(newState))
        {
            _state.store(oldState, std::memory_order_relaxed);
            return std::nullopt;
        }

        return newState;
    }

    virtual bool IsStateTransitionAllowedLocked(const T fromState, const T toState) const { return toState > fromState; };

    // Return false if transition should be reverted. Last chance for the implementation to roll back changes if something critically goes wrong in this callback.
    virtual bool OnStateTransitionLocked([[maybe_unused]] const T newState) noexcept { return true; };
    virtual void OnStateTransitionUnlocked([[maybe_unused]] const T newState) noexcept {};

    mutable TMutex _state_mutex;

private:
    std::atomic<T> _state{ T{} };
};
