/*
 * AI provenance notice:
 * The initial implementation of this file was generated by OpenAI Codex from
 * requirements supplied by the repository owner. It was not manually authored
 * by the repository owner. Subsequent changes, if any, are recorded in version
 * control.
 */

#pragma once

import <atomic>;
import <cassert>;
import <compare>;
import <concepts>;
import <cstddef>;
import <iterator>;
import <memory>;
import <mutex>;
import <optional>;
import <span>;
import <type_traits>;
import <utility>;


// Any combination of std::shared_ptr and std::weak_ptr could be used here
template <typename T>
struct IsSharedOrWeakPtr : std::false_type {};

template <typename T>
struct IsSharedOrWeakPtr<std::shared_ptr<T>> : std::true_type {};

template <typename T>
struct IsSharedOrWeakPtr<std::weak_ptr<T>> : std::true_type {};

template <typename T>
concept SharedOrWeakPtr = IsSharedOrWeakPtr<std::remove_cvref_t<T>>::value;

template <SharedOrWeakPtr TPtrA, SharedOrWeakPtr TPtrB>
bool pointersHaveSameControlBlock(const TPtrA& a, const TPtrB& b)
{
    return !a.owner_before(b) && !b.owner_before(a);
}


template<typename T>
concept RingQueueElement =
	std::is_object_v<T> &&
	!std::is_const_v<T> &&
	!std::is_volatile_v<T> &&
	std::destructible<T>;


// Fixed-capacity ring buffer whose backing storage is allocated at construction.
// Ring operations never allocate or resize that storage; T's operations may.
// The container is not internally synchronized. Callers must serialize shared
// access, allowing it to participate in a larger locking protocol.
template<RingQueueElement T>
class TRingQueue final
{
public:
	using value_type = T;
	using size_type = std::size_t;
	using reference = value_type&;
	using const_reference = const value_type&;

	explicit TRingQueue(const size_type capacity)
		: capacity_(capacity)
		, storage_(capacity == 0 ? nullptr : AllocatorTraits::allocate(allocator_, capacity))
	{
	}

	~TRingQueue()
	{
		reset();
	}

	TRingQueue(const TRingQueue&) = delete;
	TRingQueue& operator=(const TRingQueue&) = delete;

	TRingQueue(TRingQueue&& other) noexcept
		: capacity_(std::exchange(other.capacity_, 0))
		, size_(std::exchange(other.size_, 0))
		, head_(std::exchange(other.head_, 0))
		, tail_(std::exchange(other.tail_, 0))
		, storage_(std::exchange(other.storage_, nullptr))
	{
	}

	TRingQueue& operator=(TRingQueue&& other) noexcept
	{
		if (this != &other)
		{
			reset();

			capacity_ = std::exchange(other.capacity_, 0);
			size_ = std::exchange(other.size_, 0);
			head_ = std::exchange(other.head_, 0);
			tail_ = std::exchange(other.tail_, 0);
			storage_ = std::exchange(other.storage_, nullptr);
		}

		return *this;
	}

	[[nodiscard]] size_type capacity() const noexcept
	{
		return capacity_;
	}

	[[nodiscard]] size_type size() const noexcept
	{
		return size_;
	}

	[[nodiscard]] bool empty() const noexcept
	{
		return size_ == 0;
	}

	[[nodiscard]] bool full() const noexcept
	{
		return size_ == capacity_;
	}

	[[nodiscard]] reference front() noexcept
	{
		assert(!empty());
		return storage_[head_];
	}

	[[nodiscard]] const_reference front() const noexcept
	{
		assert(!empty());
		return storage_[head_];
	}

	[[nodiscard]] reference back() noexcept
	{
		assert(!empty());
		return storage_[tail_ == 0 ? capacity_ - 1 : tail_ - 1];
	}

	[[nodiscard]] const_reference back() const noexcept
	{
		assert(!empty());
		return storage_[tail_ == 0 ? capacity_ - 1 : tail_ - 1];
	}

	template<typename... TArguments>
		requires std::constructible_from<value_type, TArguments...>
	[[nodiscard]] bool try_emplace(TArguments&&... arguments)
	{
		if (full())
		{
			return false;
		}

		AllocatorTraits::construct(
			allocator_,
			storage_ + tail_,
			std::forward<TArguments>(arguments)...);

		tail_ = advance(tail_);
		++size_;

		return true;
	}

	[[nodiscard]] bool try_push(const value_type& value)
		requires std::constructible_from<value_type, const value_type&>
	{
		return try_emplace(value);
	}

	[[nodiscard]] bool try_push(value_type&& value)
		requires std::constructible_from<value_type, value_type&&>
	{
		return try_emplace(std::move(value));
	}

	void pop() noexcept
	{
		assert(!empty());

		AllocatorTraits::destroy(allocator_, storage_ + head_);
		head_ = advance(head_);
		--size_;
	}

	[[nodiscard]] std::optional<value_type> try_pop() noexcept
		requires std::is_nothrow_move_constructible_v<value_type>
	{
		if (empty())
		{
			return std::nullopt;
		}

		std::optional<value_type> result{
			std::in_place,
			std::move(front())
		};

		pop();
		return result;
	}

    // Moves into caller-owned objects and returns the populated portion of the
    // destination. The returned span never refers to this queue's storage.
    template <typename Predicate = std::nullptr_t>
    [[nodiscard]] std::span<value_type> pop_into(std::span<value_type> destination, Predicate&& predicate = nullptr)
        requires
            std::is_nothrow_move_constructible_v<value_type> &&
            std::is_nothrow_move_assignable_v<value_type>
    {
        const size_type originalSize = size_;
        size_type numberPopped = 0;

        for (size_type index = 0; index < originalSize; ++index)
        {
            value_type current = std::move(front());
            pop();

            bool predicatePassed = true;

            if constexpr (!std::is_same_v<std::remove_cvref_t<Predicate>, std::nullptr_t>)
            {
                predicatePassed = std::invoke(predicate, current);
            }

            if (numberPopped < destination.size() && predicatePassed)
            {
                destination[numberPopped++] = std::move(current);
            }
            else
            {
                [[maybe_unused]] const bool success = try_push(std::move(current));
                assert(success && "Failed to push inside TRingQueue's pop_into.");
            }
        }

        return destination.first(numberPopped);
    }

	void clear() noexcept
	{
		while (!empty())
		{
			pop();
		}
	}

private:
	// Random-access iterator over the ring's logical order. logicalIndex_ is a plain,
	// non-wrapping offset from head_; only dereferencing maps it onto physical storage
	// via modulo capacity_, so iterator arithmetic never needs to know about wraparound.
	// Invalidated the same way any other view of storage_/head_/tail_/size_ would be: by
	// a subsequent push, pop, clear, move, or destruction of the queue.
	template<bool IsConst>
	class Iterator
	{
	public:
		using iterator_concept = std::random_access_iterator_tag;
		using iterator_category = std::random_access_iterator_tag;
		using value_type = T;
		using difference_type = std::ptrdiff_t;
		using pointer = std::conditional_t<IsConst, const value_type*, value_type*>;
		using reference = std::conditional_t<IsConst, const value_type&, value_type&>;

		Iterator() noexcept = default;

		// Allows iterator -> const_iterator conversion. Templated on OtherIsConst (rather
		// than just taking Iterator<false>) so this is never mistaken for IsConst's own
		// copy constructor: a constructor template is never treated as a copy/move
		// constructor, even when it could match that signature after instantiation.
		template<bool OtherIsConst>
			requires (IsConst && !OtherIsConst)
		Iterator(const Iterator<OtherIsConst>& other) noexcept
			: storage_(other.storage_)
			, capacity_(other.capacity_)
			, head_(other.head_)
			, logicalIndex_(other.logicalIndex_)
		{
		}

		[[nodiscard]] reference operator*() const noexcept { return storage_[physicalIndex(0)]; }
		[[nodiscard]] pointer operator->() const noexcept { return storage_ + physicalIndex(0); }
		[[nodiscard]] reference operator[](const difference_type offset) const noexcept { return storage_[physicalIndex(offset)]; }

		Iterator& operator++() noexcept { ++logicalIndex_; return *this; }
		Iterator operator++(int) noexcept { Iterator result = *this; ++*this; return result; }
		Iterator& operator--() noexcept { --logicalIndex_; return *this; }
		Iterator operator--(int) noexcept { Iterator result = *this; --*this; return result; }

		Iterator& operator+=(const difference_type offset) noexcept { logicalIndex_ += offset; return *this; }
		Iterator& operator-=(const difference_type offset) noexcept { logicalIndex_ -= offset; return *this; }

		[[nodiscard]] friend Iterator operator+(Iterator it, const difference_type offset) noexcept { it += offset; return it; }
		[[nodiscard]] friend Iterator operator+(const difference_type offset, Iterator it) noexcept { it += offset; return it; }
		[[nodiscard]] friend Iterator operator-(Iterator it, const difference_type offset) noexcept { it -= offset; return it; }
		[[nodiscard]] friend difference_type operator-(const Iterator& left, const Iterator& right) noexcept { return left.logicalIndex_ - right.logicalIndex_; }

		[[nodiscard]] friend bool operator==(const Iterator&, const Iterator&) noexcept = default;
		[[nodiscard]] friend auto operator<=>(const Iterator& left, const Iterator& right) noexcept { return left.logicalIndex_ <=> right.logicalIndex_; }

	private:
		friend class TRingQueue;
		friend class Iterator<!IsConst>;

		using StoragePointer = std::conditional_t<IsConst, const value_type*, value_type*>;

		Iterator(StoragePointer storage, const size_type capacity, const size_type head, const difference_type logicalIndex) noexcept
			: storage_(storage)
			, capacity_(capacity)
			, head_(head)
			, logicalIndex_(logicalIndex)
		{
		}

		[[nodiscard]] size_type physicalIndex(const difference_type offset) const noexcept
		{
			return (head_ + static_cast<size_type>(logicalIndex_ + offset)) % capacity_;
		}

		StoragePointer storage_ = nullptr;
		size_type capacity_ = 0;
		size_type head_ = 0;
		difference_type logicalIndex_ = 0;
	};

public:
	using iterator = Iterator<false>;
	using const_iterator = Iterator<true>;

	[[nodiscard]] iterator begin() noexcept { return iterator(storage_, capacity_, head_, 0); }
	[[nodiscard]] iterator end() noexcept { return iterator(storage_, capacity_, head_, static_cast<std::ptrdiff_t>(size_)); }
	[[nodiscard]] const_iterator begin() const noexcept { return const_iterator(storage_, capacity_, head_, 0); }
	[[nodiscard]] const_iterator end() const noexcept { return const_iterator(storage_, capacity_, head_, static_cast<std::ptrdiff_t>(size_)); }
	[[nodiscard]] const_iterator cbegin() const noexcept { return begin(); }
	[[nodiscard]] const_iterator cend() const noexcept { return end(); }

private:
	using AllocatorType = std::allocator<value_type>;
	using AllocatorTraits = std::allocator_traits<AllocatorType>;

	[[nodiscard]] size_type advance(const size_type index) const noexcept
	{
		return index + 1 == capacity_ ? 0 : index + 1;
	}

	void reset() noexcept
	{
		clear();

		if (storage_ != nullptr)
		{
			AllocatorTraits::deallocate(allocator_, storage_, capacity_);
		}

		capacity_ = 0;
		head_ = 0;
		tail_ = 0;
		storage_ = nullptr;
	}

	[[no_unique_address]] AllocatorType allocator_;
	size_type capacity_ { 0 };
	size_type size_ { 0 };
	size_type head_ { 0 };
	size_type tail_ { 0 };
	value_type* storage_ { nullptr };
};

enum class TStateMachineState
{
    NotStarted = 0,
    InProgress,
    Stopped,
};

template <typename T>
concept BasicLockable =
    requires(T mutex)
{
    mutex.lock();
    mutex.unlock();
};

template<typename T = TStateMachineState, typename TMutex = std::mutex>
    requires
        std::is_trivially_copyable_v<T> &&
        std::semiregular<T> &&
        std::totally_ordered<T> &&
        BasicLockable<TMutex>
class TStateMachine
{
public:

    [[nodiscard]] T getState() const noexcept { return state_.load(std::memory_order_relaxed); }

    // Returns the new state if transition was successful
    virtual std::optional<T> switchToState(const T newState)
    {
        std::unique_lock<TMutex> lock(stateMutex_);

        const std::optional<T> result = switchToStateLocked(lock, newState);

        if (result)
        {
            lock.unlock();
            onStateTransitionUnlocked(newState);
        }

        return result;
    }

protected:

    virtual ~TStateMachine() = default;

    // Same as switchToState, but the caller must already hold stateMutex_.
    // On success, the caller is responsible for calling
    // onStateTransitionUnlocked(newState) itself, after unlocking.
    std::optional<T> switchToStateLocked(const std::unique_lock<TMutex>& stateLock, const T newState)
    {
        if (!stateLock.owns_lock() || stateLock.mutex() != &stateMutex_)
        {
            assert(false && "switchToStateLocked requires this state machine's mutex.");
            return std::nullopt;
        }

        const auto oldState = getState();

        if ((oldState == newState) || !isStateTransitionAllowedLocked(oldState, newState))
        {
            return std::nullopt;
        }

        state_.store(newState, std::memory_order_relaxed);

        if (!onStateTransitionLocked(newState))
        {
            state_.store(oldState, std::memory_order_relaxed);
            return std::nullopt;
        }

        return newState;
    }

    virtual bool isStateTransitionAllowedLocked(const T fromState, const T toState) const { return toState > fromState; };

    // Return false if transition should be reverted. Last chance for the implementation to roll back changes if something critically goes wrong in this callback.
    virtual bool onStateTransitionLocked([[maybe_unused]] const T newState) noexcept { return true; };
    virtual void onStateTransitionUnlocked([[maybe_unused]] const T newState) noexcept {};

    mutable TMutex stateMutex_;

private:
    std::atomic<T> state_{ T{} };
};
